### ISSUE TITLE
Composer laravel require version is outdated

### ISSUE THREAD

**Issue by kolexndr** [hamjoint/mustard#3]
Hi, i see your last commit has a lot of changes. One change is move to Laraval 5.2 and its 'web' middleware group feature, but composer
still have this require line: "laravel/framework": "^5.0".

**Comment by tjbp** [comment]
`^5.0` will match any minor version above 5.0, so anything up to 6.0 - after a `composer update` you should see the framework version is 5.2 in `composer.lock`.

**Comment by kolexndr** [comment]
Actually it doesn't work so in my case.  I do not know why, because composer documentaion is similar to what you wrote about caret symbol in version format. I'm using latest composer version (updated it yesterday specially), but it didn't updated laravel to 5.2. unless i've changed version to "5.2.*".  Probabaly something wrong at my side. Sorry.
