### ISSUE TITLE
Some fixes i've made

### ISSUE THREAD

**Issue by kolexndr** [hamjoint/mustard#4]
Hi, i'm still trying to launch your application with all modules installed.
During this process i've found some errors. What is the best and easiest way for you to get my modifications for review and probably apply to your sources?  Can i send you .patch file? What do you think?

**Comment by tjbp** [comment]
There will still be errors until a stable version is released - not everything is coded nor committed yet. Feel free to fork and create a [pull request](https://help.github.com/articles/creating-a-pull-request/) though.

**Comment by kolexndr** [comment]
ok. Thank you.
